import React, { useEffect, useState } from 'react';
import { Calendar, CheckCircle2, Clock, LogOut, MapPin, Plus, ShieldCheck, UserRound } from 'lucide-react';
import { adminApi, appointmentsApi, availabilityApi, catalogsApi, schedulingErrorMessage } from '../api/schedulingApi';
import type { Appointment, AvailabilityBlock, CatalogItem, Professional, Specialty, User } from '../types';

interface Props { user: User; onOpenBooking: () => void; onLogout: () => void; }
const heading = (role: string) => role === 'ADMIN' ? 'Administración de la oferta' : role === 'PROFESSIONAL' ? 'Mi disponibilidad' : 'Agenda tu atención';

export function DashboardScreen({ user, onOpenBooking, onLogout }: Props) {
  const role = user.roles?.includes('ADMIN') ? 'ADMIN' : user.roles?.includes('PROFESSIONAL') ? 'PROFESSIONAL' : 'USER';
  return <div className="w-full max-w-6xl mx-auto space-y-6 pb-12" id="portal-dashboard">
    <header className="bg-white rounded-2xl shadow-sm border border-slate-100 px-6 py-4 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-blue-600 to-sky-400 text-white flex items-center justify-center shadow-md"><Calendar className="w-5 h-5" /></div><div><strong className="block text-slate-900">Portal de Citas</strong><span className="text-xs text-slate-400 uppercase">{heading(role)}</span></div></div><div className="flex items-center gap-3"><div className="hidden sm:block text-right"><strong className="block text-sm text-slate-900">{user.name}</strong><span className="text-xs text-slate-400">{role}</span></div>{role === 'USER' && <button type="button" onClick={onOpenBooking} className="px-4 py-2.5 bg-blue-600 text-white text-xs font-semibold rounded-xl"><Plus className="inline w-4 h-4 mr-1" />Agendar cita</button>}<button type="button" onClick={onLogout} title="Cerrar sesión" className="p-2 text-slate-400 hover:text-red-600"><LogOut className="w-5 h-5" /></button></div></header>
    {role === 'USER' ? <UserHome onOpenBooking={onOpenBooking} /> : role === 'ADMIN' ? <AdminHome /> : <ProfessionalHome />}
    <footer className="p-4 bg-white rounded-2xl border border-slate-100 text-center text-xs text-slate-500"><ShieldCheck className="inline w-4 h-4 text-emerald-600 mr-1" />Portal de Citas Médicas · datos sintéticos de laboratorio</footer>
  </div>;
}

function UserHome({ onOpenBooking }: { onOpenBooking: () => void }) { return <section className="bg-white rounded-3xl p-8 shadow-sm border border-slate-100 text-center space-y-4"><div className="w-14 h-14 mx-auto bg-blue-50 rounded-2xl text-blue-600 flex items-center justify-center"><Calendar /></div><h1 className="text-2xl font-bold text-slate-900">Encuentra un horario disponible</h1><p className="max-w-xl mx-auto text-sm text-slate-500">Selecciona sede, especialidad, profesional y horario. El sistema confirma la disponibilidad al enviar la solicitud.</p><button type="button" onClick={onOpenBooking} className="px-5 py-3 bg-blue-600 text-white text-sm font-semibold rounded-xl">Buscar y agendar</button></section>; }

function AdminHome() {
  const [specialties, setSpecialties] = useState<Specialty[]>([]); const [pending, setPending] = useState<Appointment[]>([]); const [error, setError] = useState(''); const [name, setName] = useState(''); const [code, setCode] = useState(''); const [duration, setDuration] = useState<30 | 60>(30); const [general, setGeneral] = useState(false); const [reasons, setReasons] = useState<Record<string, string>>({});
  const load = () => Promise.all([adminApi.specialties(), appointmentsApi.pendingSpecialized()]).then(([s, a]) => { setSpecialties(s); setPending(a); }).catch((cause) => setError(schedulingErrorMessage(cause)));
  useEffect(() => { load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim() || !code.trim()) return; try { await adminApi.createSpecialty({ code: code.trim(), name: name.trim(), durationMinutes: duration, general }); setName(''); setCode(''); setGeneral(false); await load(); } catch (cause) { setError(schedulingErrorMessage(cause)); } };
  const decide = async (appointment: Appointment, decision: 'APPROVE' | 'REJECT') => { const rejectionReason = reasons[appointment.id]?.trim(); if (decision === 'REJECT' && !rejectionReason) { setError('El rechazo requiere un motivo.'); return; } try { await appointmentsApi.decide(appointment.id, decision, rejectionReason); await load(); } catch (cause) { setError(schedulingErrorMessage(cause)); } };
  return <div className="grid lg:grid-cols-2 gap-6">{error && <p role="alert" className="lg:col-span-2 p-3 text-sm text-red-700 bg-red-50 rounded-xl">{error}</p>}<section className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 space-y-4"><h2 className="text-lg font-bold">Especialidades</h2><form onSubmit={create} className="grid grid-cols-2 gap-2"><input value={code} onChange={(event) => setCode(event.target.value)} placeholder="Código" className="p-2 border rounded-xl text-sm" /><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Nueva especialidad" className="p-2 border rounded-xl text-sm" /><select value={duration} onChange={(event) => setDuration(Number(event.target.value) as 30 | 60)} className="p-2 border rounded-xl text-sm"><option value={30}>30 min</option><option value={60}>60 min</option></select><label className="text-xs p-2"><input type="checkbox" checked={general} onChange={(event) => setGeneral(event.target.checked)} /> Medicina general</label><button className="col-span-2 px-3 py-2 bg-blue-600 text-white rounded-xl text-xs font-semibold">Crear especialidad</button></form><div className="space-y-2">{specialties.map((item) => <div key={item.id} className="p-3 bg-slate-50 rounded-xl flex justify-between text-sm"><span>{item.name}</span><span className="text-slate-500">{item.durationMinutes} min · {item.active === false ? 'Inactiva' : 'Activa'}</span></div>)}</div></section><section className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 space-y-3"><h2 className="text-lg font-bold">Profesionales y asignaciones</h2><p className="text-sm text-slate-500">La API administra la creación, asignación de especialidades y sedes, y activación de profesionales. La pantalla de gestión completa de profesionales sigue pendiente del siguiente incremento.</p></section><section className="lg:col-span-2 bg-white rounded-3xl p-6 shadow-sm border border-slate-100 space-y-3"><h2 className="text-lg font-bold">Solicitudes especializadas pendientes</h2>{pending.length ? pending.map((item) => <div key={item.id} className="p-4 border rounded-xl grid md:grid-cols-[1fr_auto] gap-3"><div><strong>{item.professionalName}</strong><p className="text-xs text-slate-500">{item.specialtyName} · {item.locationName} · {item.startAt}</p><input value={reasons[item.id] ?? ''} onChange={(event) => setReasons({ ...reasons, [item.id]: event.target.value })} placeholder="Motivo obligatorio si rechaza" className="mt-2 p-2 border rounded-lg text-xs w-full md:max-w-md" /></div><div className="flex gap-2"><button type="button" onClick={() => decide(item, 'APPROVE')} className="px-3 py-2 text-xs bg-emerald-600 text-white rounded-xl">Aprobar</button><button type="button" onClick={() => decide(item, 'REJECT')} className="px-3 py-2 text-xs bg-red-600 text-white rounded-xl">Rechazar</button></div></div>) : <p className="text-sm text-slate-500">No hay solicitudes especializadas pendientes.</p>}</section></div>;
}

function ProfessionalHome() {
  const [locations, setLocations] = useState<CatalogItem[]>([]); const [blocks, setBlocks] = useState<AvailabilityBlock[]>([]); const [locationId, setLocationId] = useState(''); const [startAt, setStartAt] = useState(''); const [endAt, setEndAt] = useState(''); const [error, setError] = useState('');
  const load = () => availabilityApi.listMine().then(setBlocks).catch((cause) => setError(schedulingErrorMessage(cause)));
  useEffect(() => { catalogsApi.locations().then(setLocations).catch((cause) => setError(schedulingErrorMessage(cause))); load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); try { await availabilityApi.create({ locationId, startAt, endAt }); setLocationId(''); setStartAt(''); setEndAt(''); await load(); } catch (cause) { setError(schedulingErrorMessage(cause)); } };
  return <div className="grid lg:grid-cols-2 gap-6">{error && <p role="alert" className="lg:col-span-2 p-3 text-sm text-red-700 bg-red-50 rounded-xl">{error}</p>}<section className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100"><h2 className="text-lg font-bold mb-4">Publicar bloque de disponibilidad</h2><form onSubmit={create} className="space-y-3"><select required value={locationId} onChange={(event) => setLocationId(event.target.value)} className="w-full p-3 border rounded-xl"><option value="">Selecciona una sede</option>{locations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><label className="block text-xs">Inicio<input required type="datetime-local" value={startAt} onChange={(event) => setStartAt(event.target.value)} className="mt-1 w-full p-3 border rounded-xl" /></label><label className="block text-xs">Fin<input required type="datetime-local" value={endAt} onChange={(event) => setEndAt(event.target.value)} className="mt-1 w-full p-3 border rounded-xl" /></label><button className="w-full py-3 bg-blue-600 text-white text-sm font-semibold rounded-xl">Publicar bloque</button></form></section><section className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100"><h2 className="text-lg font-bold mb-4">Mi calendario</h2><div className="space-y-3">{blocks.length ? blocks.map((block) => <div key={block.id} className="p-3 rounded-xl bg-slate-50 border flex justify-between gap-3 text-sm"><span><MapPin className="inline w-4 h-4 text-blue-600 mr-1" />{block.locationName ?? block.locationId}<br /><Clock className="inline w-4 h-4 text-blue-600 mr-1" />{block.startAt} — {block.endAt}</span><button type="button" onClick={async () => { try { await availabilityApi.remove(block.id); await load(); } catch (cause) { setError(schedulingErrorMessage(cause)); } }} className="text-xs text-red-600">Eliminar</button></div>) : <p className="text-sm text-slate-500">No tienes bloques publicados.</p>}</div></section></div>;
}
